# Processing race testing dataset from CloudResearch

In [1]:
import pandas as pd
import numpy as np
import json

### combining the CloudResearch datasets into one DF

In [2]:
respondent_df = pd.read_csv("race_testing_1.csv")

for i in np.arange(2, 6):
    csv = "race_testing_" + str(i) + ".csv"
    csv_df = pd.read_csv(csv)
    respondent_df = pd.concat([respondent_df, csv_df])

respondent_df

,ParticipantId,StartTime (America/Chicago),CompletionTime (America/Chicago),CompletionType,CompletionCode,Payment,Bonus,Fees,Status,Task Data,...,Education,Sex,Occupation Field,Relationship/Marital Status,Political Party,Gender,Country Of Residence,Household Income,Race,Employment Status
0,AA3A6D4244DF4C538D320436A8D9E95B,05/05/2024 12:18:15 AM,05/05/2024 12:23:58 AM,Template,NaN,0,0,0,Pending,"{""RowData"":[{""CellData"":""3.0"",""ColumnHeader"":""...",...,"Bachelor's degree (for example: BA, AB, BS)",Female,Marketing and Sales,Married,Republican,Woman,United States,"$100,000-$124,999",White,Part-time
1,AE5BB3054A9A46FABF7249C579A08B44,05/05/2024 12:18:57 AM,NaN,NaN,NaN,0,0,0,Returned,NaN,...,"Bachelor's degree (for example: BA, AB, BS)",Female,Information Technology,In a relationship,Independent,Woman,United States,"$250,000 or more",Chinese,Full-time
2,4227771CBB974D8DBE299B31F11DF2FE,05/05/2024 12:19:55 AM,05/05/2024 12:22:40 AM,Template,NaN,0,0,0,Pending,"{""RowData"":[{""CellData"":""3.0"",""ColumnHeader"":""...",...,"Some college, but no degree",Male,Social Sciences,Single,Democrat,Man,United States,"Less than $10,000",White,Student
3,D9F22A70D01245B78439FC66BF61E39F,05/05/2024 12:27:50 AM,05/05/2024 12:32:19 AM,Template,NaN,0,0,0,Pending,"{""RowData"":[{""CellData"":""3.0"",""ColumnHeader"":""...",...,"Bachelor's degree (for example: BA, AB, BS)",Female,Business Management & Administration,Married,Independent,Woman,United States,"$200,000-$224,999",White,Full-time
4,2FA543FD1C31419CB8107888D3E03B01,05/05/2024 12:30:50 AM,05/05/2024 12:33:07 AM,Template,NaN,0,0,0,Pending,"{""RowData"":[{""CellData"":""3.0"",""ColumnHeader"":""...",...,No formal education,Male,Iâ€™d Rather Not Say,Single,Something else,Man,United States,"$30,000-$39,999",White,"Not in paid work (e.g., homemaker, disabled)"
5,45CBE4E615BE45BCAD84E0992A364627,05/05/2024 12:34:31 AM,05/05/2024 12:40:56 AM,Template,NaN,0,0,0,Pending,"{""RowData"":[{""CellData"":""3.0"",""ColumnHeader"":""...",...,"Some college, but no degree",Female,Other,In a relationship,Democrat,Woman,United States,"$70,000-$79,999",White,Student
0,BA2BCA7CCB1C4030859B5BC1E915D44D,05/04/2024 10:55:23 PM,05/04/2024 11:00:12 PM,Template,NaN,0,0,0,Pending,"{""RowData"":[{""CellData"":""3.0"",""ColumnHeader"":""...",...,"Bachelor's degree (for example: BA, AB, BS)",Male,Information Technology,Married,Republican,Man,United States,"$100,000-$124,999",White,Full-time
1,26F87AAEE50B4B609820FE55FDE99B80,05/04/2024 10:55:34 PM,NaN,NaN,NaN,0,0,0,Returned,NaN,...,"Some college, but no degree",Male,Other,Single,Democrat,Man,United States,"$150,0000-$174,999",Chinese,Student
2,CB62A7BD071944C3AE37C3D8EF158156,05/04/2024 10:56:25 PM,05/04/2024 11:08:03 PM,Template,NaN,0,0,0,Pending,"{""RowData"":[{""CellData"":""3.0"",""ColumnHeader"":""...",...,"Master's degree (for example: MA, MS, MEng, ME...",Female,Other,Single,Democrat,Woman,United States,"$10,000-$19,999",Black or African American,Unemployed
3,864CE43156324300A60C5063A8335D2D,05/04/2024 10:56:27 PM,05/04/2024 11:00:13 PM,Template,NaN,0,0,0,Pending,"{""RowData"":[{""CellData"":""3.0"",""ColumnHeader"":""...",...,"Bachelor's degree (for example: BA, AB, BS)",Female,Social Sciences,Married,Republican,Woman,United States,"$40,000-$49,999",White,Full-time
4,51F86DA2D4024A27959285356C77BE28,05/04/2024 10:56:48 PM,NaN,NaN,NaN,0,0,0,Returned,NaN,...,"Some college, but no degree",Female,Other,Married,Prefer not to say,Woman,United States,"$50,000-$59,999",White,Prefer not to say
5,335F74DDC5A84FD4B92ACC2A24E95889,05/04/2024 10:59:49 PM,NaN,NaN,NaN,0,0,0,Returned,NaN,...,"Bachelor's degree (for example: BA, AB, BS)",Male,Information Technology,Married,Republican,Man,United States,"$90,000-$99,999",Black or African American,Full-time
6,0A45ED8DF2274BB2BBF6322C4837BEDA,05/04/2024 11:00:15 PM,05/04/2024 11:04:20 PM,Template,NaN,0,0,0,Pending,"{""RowData"":[{""CellData"":""3.0"",""ColumnHeader"":""...",...,"Doctorate degree (for example: PhD, EdD)",Male,Social Sciences,Single,Democrat,Man,United States,"$100,000-$124,999",White,Full-time
7,1FD76243C2D94C58ADD0958ECB3528B6,05/04/2024 11:06:54 PM,05/04/2024 11:10:27 PM,Template,NaN,0,0,0,Pending,"{""RowData"":[{""CellData"":""3.0"",""ColumnHeader"":""...",...,"Bachelor's degree (for example: BA, AB, BS)",Female,Iâ€™d Rather Not Say,Single,Democrat,Woman,United States,"Less than $10,000",White,Unemployed
0,1C8CD169FA864823AA3D114246CC4068,05/04/2024 06:48:26 PM,05/04/2024 06:54:07 PM,Template,NaN,0,0,0,Pending,"{""RowData"":[{""CellData"":""3.0"",""ColumnHeader"":""...",...,"Bachelor's degree (for example: BA, AB, BS)",Female,Legal,Married,Democrat,Woman,United States,"$125,000-$149,999",Filipino,Part-time
1,77EDCE8BEB15439F8FA887FA4A4E0CB2,05/04/2024 06:49:09 PM,05/04/2024 06:52:00 PM,Template,NaN,0,0,0,Pending,"{""RowData"":[{""CellData"":""3.0"",""ColumnHeader"":""...",...,"Bachelor's degree (for example: BA, AB, BS)",Female,Retired,Married,Independent,Woman,United States,"$150,0000-$174,999",White,Retired
2,A8559E9391AE45C7BB6721C6064C9D17,05/04/2024 06:50:00 PM,NaN,NaN,NaN,0,0,0,Returned,NaN,...,"Bachelor's degree (for example: BA, AB, BS)",Female,Iâ€™d Rather Not Say,Single,Democrat,Woman,United States,"$30,000-$39,999",Chinese,Student
3,4AAE2C300189483FA66CE257E49246E3,05/04/2024 06:50:20 PM,NaN,NaN,NaN,0,0,0,Returned,NaN,...,"Professional degree (for example: MD, DDS, DVM...",Male,Medicine,Married,Democrat,Man,United States,"$250,000 or more",White,Full-time
4,DC3B237B079F4641B3E72B071F7C10B0,05/04/2024 06:53:15 PM,05/04/2024 06:56:31 PM,Template,NaN,0,0,0,Pending,"{""RowData"":[{""CellData"":""3.0"",""ColumnHeader"":""...",...,"Associate degree (for example: AA, AS)",Male,Retail,Single,Independent,Man,United States,"$60,000-$69,999",White,Business Owner
5,4C6F8CAA432043F6A437E7B9A1716996,05/04/2024 06:53:29 PM,NaN,NaN,NaN,0,0,0,Returned,NaN,...,"Master's degree (for example: MA, MS, MEng, ME...",Male,"Transportation, Distribution & Logistics",Married,Independent,Man,United States,"$200,000-$224,999",White,Full-time
6,92FA5897100F46569201E41359A5ED7C,05/04/2024 06:54:06 PM,NaN,NaN,NaN,0,0,0,Returned,NaN,...,"Bachelor's degree (for example: BA, AB, BS)",Female,Education & Training,Married,Democrat,Woman,United States,"$30,000-$39,999",White,Full-time
7,784A96937A0F44E1BA55D7971CA37B7A,05/04/2024 06:56:37 PM,NaN,NaN,NaN,0,0,0,Returned,NaN,...,"Bachelor's degree (for example: BA, AB, BS)",Female,Other,Married,Democrat,Woman,United States,"$100,000-$124,999",White,Unemployed
8,3EF4BE756FE24DD28D45D92ECFD12899,05/04/2024 06:57:43 PM,05/04/2024 06:59:42 PM,Template,NaN,0,0,0,Pending,"{""RowData"":[{""CellData"":""3.0"",""ColumnHeader"":""...",...,"Bachelor's degree (for example: BA, AB, BS)",Male,"Science, Technology, Engineering & Mathematics",Married,Democrat,Man,United States,"$70,000-$79,999",Chinese,Full-time
9,68886BA8F3884221B3BB8719B409DBFA,05/04/2024 06:58:28 PM,05/04/2024 07:02:52 PM,Template,NaN,0,0,0,Pending,"{""RowData"":[{""CellData"":""3.0"",""ColumnHeader"":""...",...,"Some college, but no degree",Female,Retail,In a relationship,Democrat,Woman,United States,"$150,0000-$174,999",White,Full-time
0,61FFB453863242FDA4ED125D8E818F3C,05/04/2024 05:50:23 PM,05/04/2024 05:54:09 PM,Template,NaN,0,0,0,Pending,"{""RowData"":[{""CellData"":""3.0"",""ColumnHeader"":""...",...,High school graduate - high school diploma or ...,Male,Manufacturing,Single,Republican,Man,United States,"$50,000-$59,999",Black or African American,Full-time
1,7A297412E1E745A688FF810CCF05C4DE,05/04/2024 05:50:25 PM,05/04/2024 05:54:42 PM,Template,NaN,0,0,0,Pending,"{""RowData"":[{""CellData"":""3.0"",""ColumnHeader"":""...",...,"Bachelor's degree (for example: BA, AB, BS)",Male,"Transportation, Distribution & Logistics",Single,Something else,Man,United States,"$30,000-$39,999",White,Full-time
2,213D5E42CDE0440C9C5CCA79272A156A,05/04/2024 05:52:28 PM,NaN,NaN,NaN,0,0,0,Returned,NaN,...,"Associate degree (for example: AA, AS)",Female,Medicine,In a relationship,Prefer not to say,Woman,United States,"$60,000-$69,999",An ethnicity not listed here,Full-time
3,2E5D21D7783C4AF0966C6576042B4692,05/04/2024 05:54:10 PM,NaN,NaN,NaN,0,0,0,Returned,NaN,...,"Some college, but no degree",Female,Arts,Married,Democrat,Woman,United States,"$125,000-$149,999",White,Business Owner
4,5305C66A7A354BA980850775BF9E52A8,05/04/2024 05:55:54 PM,NaN,NaN,NaN,0,0,0,Returned,NaN,...,"Bachelor's degree (for example: BA, AB, BS)",Female,Finance,Single,Democrat,Woman,United States,"$40,000-$49,999",White,Part-time
5,9B9C14A8482F4C27B3DB6EBEF7149B29,05/04/2024 06:05:57 PM,NaN,NaN,NaN,0,0,0,Returned,NaN,...,"Some college, but no degree",Female,Retail,Single,Democrat,Woman,United States,"$40,000-$49,999",White,"Not in paid work (e.g., homemaker, disabled)"
6,0BD6354288E0413ABFE2A0E55BF994AD,05/04/2024 06:10:22 PM,NaN,NaN,NaN,0,0,0,Returned,NaN,...,"Some college, but no degree",Female,Other,In a relationship,Republican,Woman,United States,"$40,000-$49,999",White,Full-time
7,268A77DCC33A496DBE1C086D0717C820,05/04/2024 06:11:24 PM,NaN,NaN,NaN,0,0,0,Returned,NaN,...,High school graduate - high school diploma or ...,Female,Iâ€™d Rather Not Say,In a relationship,Republican,Woman,United States,"$20,000-$29,999",White,Unemployed
8,4D95DC404E0E4A6D941FCCF9B8001953,05/04/2024 06:14:18 PM,NaN,NaN,NaN,0,0,0,Returned,NaN,...,"Bachelor's degree (for example: BA, AB, BS)",Female,Social Sciences,Divorced,Republican,Woman,United States,"$70,000-$79,999",White,Full-time
9,E221924AFFA44D3C954FBCC53940D16F,05/04/2024 06:17:10 PM,NaN,NaN,NaN,0,0,0,Returned,NaN,...,"Some college, but no degree",Female,Retired,Married,Republican,Woman,United States,"$70,000-$79,999",White,Retired
10,B2E5FF75A2FA46979E78ACDC2F81BD5C,05/04/2024 06:17:19 PM,NaN,NaN,NaN,0,0,0,Returned,NaN,...,High school graduate - high school diploma or ...,Female,Retail,Single,Democrat,Woman,United States,"$50,000-$59,999",White,Full-time
11,BE2B4E821DD24946833615555D3606B5,05/04/2024 06:17:58 PM,05/04/2024 06:21:24 PM,Template,NaN,0,0,0,Pending,"{""RowData"":[{""CellData"":""3.0"",""ColumnHeader"":""...",...,"Bachelor's degree (for example: BA, AB, BS)",Female,Education & Training,Single,Independent,Woman,United States,Prefer not to say,An ethnicity not listed here,Student
12,3D2E1ADC0C4F4372BF8E782C3FED8E7F,05/04/2024 06:19:12 PM,NaN,NaN,NaN,0,0,0,Returned,NaN,...,"Master's degree (for example: MA, MS, MEng, ME...",Female,Information Technology,In a relationship,Something else,Woman,United States,"$40,000-$49,999",White,Part-time
13,11316DAF4C0C4F738B0B9AD73C88CB3E,05/04/2024 06:35:32 PM,NaN,NaN,NaN,0,0,0,Returned,NaN,...,"Master's degree (for example: MA, MS, MEng, ME...",Female,Other,Married,Republican,Woman,United States,"$100,000-$124,999",White,"Not in paid work (e.g., homemaker, disabled)"
14,6071D09787B54E07879D8BD9782B2341,05/04/2024 06:38:09 PM,05/04/2024 06:41:49 PM,Template,NaN,0,0,0,Pending,"{""RowData"":[{""CellData"":""3.0"",""ColumnHeader"":""...",...,"Master's degree (for example: MA, MS, MEng, ME...",Female,Social Sciences,In a relationship,Democrat,Woman,United States,"$50,000-$59,999",White,Part-time
15,D4C87E0001BA42F491A4C60F19B7E78E,05/04/2024 06:40:42 PM,05/04/2024 06:48:08 PM,Template,NaN,0,0,0,Pending,"{""RowData"":[{""CellData"":""3.0"",""ColumnHeader"":""...",...,"Doctorate degree (for example: PhD, EdD)",Female,Education & Training,Married,Democrat,Woman,United States,"$175,000-$199,999",White,Full-time
0,84EF3A4660034354B098DECA683C4357,05/04/2024 10:58:06 PM,NaN,NaN,NaN,0,0,0,Returned,NaN,...,"Associate degree (for example: AA, AS)",Male,Arts,Single,Independent,Man,United States,"Less than $10,000",Vietnamese,Student
1,C697C1558F8149498D65C17025EB6CBB,05/04/2024 10:58:38 PM,05/04/2024 11:02:28 PM,Template,NaN,0,0,0,Pending,"{""RowData"":[{""CellData"":""3.0"",""ColumnHeader"":""...",...,"Associate degree (for example: AA, AS)",Female,Retired,Single,Independent,Woman,United States,"$10,000-$19,999",White,"Not in paid work (e.g., homemaker, disabled)"
2,1FF56911DE2F4FB1B0ECE0A44269A914,05/04/2024 10:59:08 PM,05/04/2024 11:04:14 PM,Template,NaN,0,0,0,Pending,"{""RowData"":[{""CellData"":""3.0"",""ColumnHeader"":""...",...,"Master's degree (for example: MA, MS, MEng, ME...",Male,Information Technology,Married,Prefer not to say,Man,United States,"$150,0000-$174,999",Other,Full-time
3,AC648DADC5F64379ACF56322DDA70284,05/04/2024 11:00:50 PM,05/04/2024 11:04:39 PM,Template,NaN,0,0,0,Pending,"{""RowData"":[{""CellData"":""3.0"",""ColumnHeader"":""...",...,"Some college, but no degree",Male,Information Technology,Single,Democrat,Man,United States,"$30,000-$39,999",Black or African American,Unemployed
4,9D3CED7CE0824221846EB1322A3D82DB,05/04/2024 11:00:57 PM,05/04/2024 11:05:01 PM,Template,NaN,0,0,0,Pending,"{""RowData"":[{""CellData"":""3.0"",""ColumnHeader"":""...",...,"Bachelor's degree (for example: BA, AB, BS)",Female,"Science, Technology, Engineering & Mathematics",Married,Independent,Woman,United States,"$250,000 or more",Vietnamese,Full-time
5,F3E17CB8F8EE4D53B398EA5999B203A5,05/04/2024 11:01:55 PM,NaN,NaN,NaN,0,0,0,Returned,NaN,...,High school graduate - high school diploma or ...,Female,"Transportation, Distribution & Logistics",In a relationship,Independent,Woman,United States,"$20,000-$29,999",White,Part-time
6,48336A322C2247CBA0D3135FC778C18E,05/04/2024 11:13:21 PM,05/04/2024 11:17:18 PM,Template,NaN,0,0,0,Pending,"{""RowData"":[{""CellData"":""3.0"",""ColumnHeader"":""...",...,"Bachelor's degree (for example: BA, AB, BS)",Female,Medicine,Married,Republican,Woman,United States,"$150,0000-$174,999",White,Full-time

### cleaning and formatting df

In [3]:
respondent_df.columns

Index(['ParticipantId', 'StartTime (America/Chicago)',
       'CompletionTime (America/Chicago)', 'CompletionType', 'CompletionCode',
       'Payment', 'Bonus', 'Fees', 'Status', 'Task Data', 'Submitted Data',
       'Age', 'Education', 'Sex', 'Occupation Field',
       'Relationship/Marital Status', 'Political Party', 'Gender',
       'Country Of Residence', 'Household Income', 'Race',
       'Employment Status'],
      dtype='object')

In [4]:
# want only actual responses (responses that are "Pending")

respondent_df = respondent_df[respondent_df["Status"] == "Pending"]

In [5]:
relevant_columns = ['ParticipantId', 'Task Data', 'Submitted Data',
       'Age', 'Education', 'Sex', 'Occupation Field',
       'Relationship/Marital Status', 'Political Party', 'Gender',
       'Country Of Residence', 'Household Income', 'Race',
       'Employment Status']

respondent_df = respondent_df[relevant_columns]
respondent_df = respondent_df.reset_index(drop = True)

In [6]:
respondent_demographics_df = respondent_df.drop(columns = ["Task Data", "Submitted Data"])

In [7]:
respondent_data_df = respondent_df[["Task Data", "Submitted Data"]]

In [8]:
respondent_data_df["Submitted Data"][0]

'{"Data":{"taskData":{"age":"50\\u0027s","jaw":"triangle shaped, not strongly defined ","eyes":"almond shaped, brown ","hair":"straight gray","nose":"long and pointy, large nostrils","race":"white","beard":"no","gender":"male","eyebrows":"slightly bushy gray","expression":"smiling","additionalInfo":"Slight "}}}'

In [18]:
def get_data_from_json(task_json: str, task: bool):
    """
    Returns the value associated with the given field attribute (ex: Race, Memorable)
    Args:
        field: the specific field that is being retrieved from the JSON 
        task: Boolean True if it is task data, False if it is respondent data (accessing JSON differs)
    """
    json_object = json.loads(task_json)
    if task: 
        json_object_rows = json_object["RowData"]
        task_columns = [row["ColumnHeader"] for row in json_object_rows]
        task_columns = [column + "_og_img" for column in task_columns]
        json_object_row_headers_values = [row["CellData"] for row in json_object_rows]
        res_dict = {task_columns[i]: json_object_row_headers_values[i] for i in range(len(task_columns))}
        return res_dict
    else:
        json_object_rows = json_object["Data"]
        description_data = json_object_rows["taskData"]
        description_headers = ([*description_data.keys()])
        description_headers = [column + "_description" for column in description_headers]
        description_values = ([*description_data.values()])
        res_dict = {description_headers[i]: description_values[i] for i in range(len(description_values))}
        return res_dict

In [19]:
def reconstruct_output_df(respondent_df):
    """
    Returns the value associated with the given field attribute (ex: Race, Memorable)
    Args:
        field: the specific field that is being retrieved from the JSON 
        task: Boolean True if it is task data, False if it is respondent data (accessing JSON differs)
    """
    
    # creating the new columns for each row of the task data
    expanded_task_data = respondent_df.apply(lambda row: get_data_from_json(row["Task Data"], task = True), axis = 1, result_type = 'expand')
    respondent_df = pd.concat([expanded_task_data, respondent_df], axis = "columns")

    # getting the columns associated with one respondent description (same for all respondents so generalizable to other rows)
    expanded_description_data = respondent_df.apply(lambda row: get_data_from_json(row["Submitted Data"], task = False), axis = 1, result_type = 'expand')
    respondent_df = pd.concat([expanded_description_data, respondent_df], axis = "columns")
    
    return respondent_df

In [20]:
race_testing_df = reconstruct_output_df(respondent_df)

In [21]:
race_testing_df.to_csv("race_testing_output.csv", mode="w", index=False)

In [22]:
race_testing_df

,age_description,jaw_description,eyes_description,hair_description,nose_description,race_description,beard_description,gender_description,eyebrows_description,expression_description,...,Education,Sex,Occupation Field,Relationship/Marital Status,Political Party,Gender,Country Of Residence,Household Income,Race,Employment Status
0,50's,"triangle shaped, not strongly defined","almond shaped, brown",straight gray,"long and pointy, large nostrils",white,no,male,slightly bushy gray,smiling,...,"Bachelor's degree (for example: BA, AB, BS)",Female,Marketing and Sales,Married,Republican,Woman,United States,"$100,000-$124,999",White,Part-time
1,mid 40s,Wide,Big nose,Big brown eyebrows,Wide and,black,Non visible,male,Brown but looks black,smiling,...,"Some college, but no degree",Male,Social Sciences,Single,Democrat,Man,United States,"Less than $10,000",White,Student
2,32,normal,"dark, slanted",appears to be straight,wide,asian,none,female,thin,smiling,...,"Bachelor's degree (for example: BA, AB, BS)",Female,Business Management & Administration,Married,Independent,Woman,United States,"$200,000-$224,999",White,Full-time
3,mid-40s,round jaw,brown,thinning black,pointy nose,middle_eastern_south_asian,none,male,blaack,smiling,...,No formal education,Male,Iâ€™d Rather Not Say,Single,Something else,Man,United States,"$30,000-$39,999",White,"Not in paid work (e.g., homemaker, disabled)"
4,Mid 40s,Oval,"Small and hazel, hooded","Pulled back, tightly coiled, curly, dark brown","Short bridge, flared nostrils, flat base",hispanic,None,female,Thin dark brown and arched,smiling,...,"Some college, but no degree",Female,Other,In a relationship,Democrat,Woman,United States,"$70,000-$79,999",White,Student
5,mid-50s,Square,Small brown,Short straight brown,Long and rounded,white,None,male,Thick brown,smiling,...,"Bachelor's degree (for example: BA, AB, BS)",Male,Information Technology,Married,Republican,Man,United States,"$100,000-$124,999",White,Full-time
6,mid-20's,rounded,small brown eyes,straight black hair,small stouty,asian,None,female,slightly thin eyebrows,smiling,...,"Master's degree (for example: MA, MS, MEng, ME...",Female,Other,Single,Democrat,Woman,United States,"$10,000-$19,999",Black or African American,Unemployed
7,Mid 30s,Rounded,Large black,Short,Flat large nostrils,middle_eastern_south_asian,No beard,male,Thick black,smiling,...,"Bachelor's degree (for example: BA, AB, BS)",Female,Social Sciences,Married,Republican,Woman,United States,"$40,000-$49,999",White,Full-time
8,mid-50s,"Medium, square",Large brown,bald,"Large nose, flared nostrils",black,"Medium moustache, small chin patch",male,"Medium, grey/white and black",smiling,...,"Doctorate degree (for example: PhD, EdD)",Male,Social Sciences,Single,Democrat,Man,United States,"$100,000-$124,999",White,Full-time
9,40,N/A,White average,Wavy brown,Average,white,Smiling,female,Brown,smiling,...,"Bachelor's degree (for example: BA, AB, BS)",Female,Iâ€™d Rather Not Say,Single,Democrat,Woman,United States,"Less than $10,000",White,Unemployed
10,late 40's,squarish,squinted brown,moderate straight graying brown,straight,white,none,male,moderate brown,smiling,...,"Bachelor's degree (for example: BA, AB, BS)",Female,Legal,Married,Democrat,Woman,United States,"$125,000-$149,999",Filipino,Part-time
11,50s,rounded,"large, brown","short, tight, curly black with gray",wide and rounded,black,none,male,"thick ,dark",smiling,...,"Bachelor's degree (for example: BA, AB, BS)",Female,Retired,Married,Independent,Woman,United States,"$150,0000-$174,999",White,Retired
12,Mid 40s,Rounded,Small brown,Short and brown,Wide nostril and a long bridge,asian,None,male,Thick and small,smiling,...,"Associate degree (for example: AA, AS)",Male,Retail,Single,Independent,Man,United States,"$60,000-$69,999",White,Business Owner
13,early 30s,slightly round,dark brown,long straight black,normal,asian,none,female,thick black,smiling,...,"Bachelor's degree (for example: BA, AB, BS)",Male,"Science, Technology, Engineering & Mathematics",Married,Democrat,Man,United States,"$70,000-$79,999",Chinese,Full-time
14,Late 30s,Round,Small and brown,Long curly brunette,Small nostrils not pointed,hispanic,None,female,Thick brown,smiling,...,"Some college, but no degree",Female,Retail,In a relationship,Democrat,Woman,United States,"$150,0000-$174,999",White,Full-time
15,mid 40s,short pointed,small light brown,short brown hair with some graying,long pointed nose,white,None,male,thin brown,smiling,...,High school graduate - high school diploma or ...,Male,Manufacturing,Single,Republican,Man,United States,"$50,000-$59,999",Black or African American,Full-time
16,50s,rounded,brown,graying,large,black,none,male,dark,smiling,...,"Bachelor's degree (for example: BA, AB, BS)",Male,"Transportation, Distribution & Logistics",Single,Something else,Man,United States,"$30,000-$39,999",White,Full-time
17,mid 30s,oval jaw,large brown,thin coarse,small nostrils,asian,none,female,brown,smiling,...,"Bachelor's degree (for example: BA, AB, BS)",Female,Education & Training,Single,Independent,Woman,United States,Prefer not to say,An ethnicity not listed here,Student
18,40s,round,average brown,"brown, frizzy, in a bun or ponytail",wide,hispanic,none,female,medium brown,smiling,...,"Master's degree (for example: MA, MS, MEng, ME...",Female,Social Sciences,In a relationship,Democrat,Woman,United States,"$50,000-$59,999",White,Part-time
19,early 40s,squishy jaw with a pointed chin,"brown, not especially large","Short brown hair, thinning on top",straight long nose with a wide bottom,middle_eastern_south_asian,no beard but pronounced stuble on his chin and...,male,"normal width brown, slightly sparse",smiling,...,"Doctorate degree (for example: PhD, EdD)",Female,Education & Training,Married,Democrat,Woman,United States,"$175,000-$199,999",White,Full-time
20,Late 40s,Unremarkable,Small brown,Short blonde,Thin,white,None,male,Thin blonde,smiling,...,"Associate degree (for example: AA, AS)",Female,Retired,Single,Independent,Woman,United States,"$10,000-$19,999",White,"Not in paid work (e.g., homemaker, disabled)"
21,55,oval,large black,black,slightly wide and pointed,black,none,male,black,other,...,"Master's degree (for example: MA, MS, MEng, ME...",Male,Information Technology,Married,Prefer not to say,Man,United States,"$150,0000-$174,999",Other,Full-time
22,late 20s,round jaw,medium size and brown,long brown,"smallish nostrils, normal sized nose",asian,NaN,female,thin same color as hair,smiling,...,"Some college, but no degree",Male,Information Technology,Single,Democrat,Man,United States,"$30,000-$39,999",Black or African American,Unemployed
23,Late 30s,Square,Large black,Short thin hair,Large nose,asian,No beard,male,Short thick brown,smiling,...,"Bachelor's degree (for example: BA, AB, BS)",Female,"Science, Technology, Engineering & Mathematics",Married,Independent,Woman,United States,"$250,000 or more",Vietnamese,Full-time
24,32,Round,Medium,Light brown straight,small narrow,hispanic,None,female,Thin,smiling,...,"Bachelor's degree (for example: BA, AB, BS)",Female,Medicine,Married,Republican,Woman,United States,"$150,0000-$174,999",White,Full-time